import { ClerkProvider } from "@clerk/nextjs"
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Topbar from "@/components/shared/Topbar"
import RightSideBar from "@/components/shared/RightSideBar"
import LeftSideBar from "@/components/shared/LeftSideBar"
import Bottombar from "@/components/shared/Bottombar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Topbar />  
            <main className="flex flex-row">
              <LeftSideBar />

              <section className="main-container">
                <div className="w-full max-w-4xl">
                  {children}
                </div>
              </section>

              <RightSideBar />
            </main>
          <Bottombar />
        </body>
      </html>
    </ClerkProvider>
    
  )
}
